import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../services/api_service.dart';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class ScanHistoryScreen extends StatefulWidget {
  const ScanHistoryScreen({Key? key}) : super(key: key);

  @override
  State<ScanHistoryScreen> createState() => _ScanHistoryScreenState();
}

class _ScanHistoryScreenState extends State<ScanHistoryScreen> {
  bool _isLoading = true;
  List<dynamic> _scans = [];
  String? _userName;

  @override
  void initState() {
    super.initState();
    _fetchHistory();
  }

  Future<void> _fetchHistory() async {
    final SharedPreferences prefs = await SharedPreferences.getInstance();
    final String? token = prefs.getString('userToken');
    _userName = prefs.getString('userName') ?? "Patient";
    
    if (token == null) {
      if (mounted) Navigator.pop(context);
      return;
    }

    final result = await ApiService.getScanHistory(token);
    if (mounted) {
      setState(() {
        if (result['history'] != null) {
          _scans = result['history'];
        }
        _isLoading = false;
      });
    }
  }

  Future<void> _generatePdf(dynamic scan) async {
    final pdf = pw.Document();
    final date = DateTime.parse(scan['timestamp']);
    final formattedDate = DateFormat('MMM dd, yyyy - hh:mm a').format(date);

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(
                level: 0,
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text("DermaAI Analysis Report", style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.teal)),
                    pw.Text("ID: ${scan['id'].toString().substring(0, 8)}"),
                  ],
                ),
              ),
              pw.SizedBox(height: 20),
              pw.Text("Patient Name: $_userName", style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
              pw.Text("Report Date: $formattedDate"),
              pw.Divider(thickness: 1, color: PdfColors.grey300),
              pw.SizedBox(height: 20),
              pw.Text("Analysis Summary", style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 10),
              pw.Container(
                padding: const pw.EdgeInsets.all(16),
                decoration: pw.BoxDecoration(
                  color: PdfColors.teal50,
                  borderRadius: const pw.BorderRadius.all(pw.Radius.circular(10)),
                ),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Row(
                      children: [
                        pw.Text("Detected Condition: ", style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                        pw.Text("${scan['prediction']}"),
                      ],
                    ),
                    pw.SizedBox(height: 8),
                    pw.Row(
                      children: [
                        pw.Text("Confidence Level: ", style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                        pw.Text("${scan['confidence'].toStringAsFixed(2)}%"),
                      ],
                    ),
                  ],
                ),
              ),
              pw.SizedBox(height: 30),
              pw.Text("Medical Note:", style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
              pw.Text(
                "This report is generated by an artificial intelligence model and is intended for informational purposes only. Please consult with a certified dermatologist for clinical diagnosis and treatment planning.",
                style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700),
              ),
              pw.Spacer(),
              pw.Divider(thickness: 0.5),
              pw.Center(child: pw.Text("Generated by DermaAI - Your Personal Skin Assistant", style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey500))),
            ],
          );
        },
      ),
    );

    await Printing.layoutPdf(onLayout: (PdfPageFormat format) async => pdf.save());
  }

  // ── Color helpers ──
  Color _confidenceColor(double c) {
    if (c >= 85) return const Color(0xFF00B894);
    if (c >= 60) return const Color(0xFFFFAB2E);
    return const Color(0xFFFF6B6B);
  }

  String _confidenceLabel(double c) {
    if (c >= 85) return 'High';
    if (c >= 60) return 'Medium';
    return 'Low';
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF4F6FB),
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0,
        scrolledUnderElevation: 1,
        surfaceTintColor: Colors.transparent,
        centerTitle: true,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios_rounded, size: 18, color: Color(0xFF1A2340)),
          onPressed: () => Navigator.pop(context),
        ),
        title: const Text(
          "My Reports",
          style: TextStyle(
            color: Color(0xFF1A2340),
            fontWeight: FontWeight.w800,
            fontSize: 17,
            letterSpacing: -0.3,
          ),
        ),
        bottom: PreferredSize(
          preferredSize: const Size.fromHeight(1),
          child: Container(height: 1, color: const Color(0xFFE5EAF4)),
        ),
      ),
      body: _isLoading
          ? const Center(child: CircularProgressIndicator(
              color: Color(0xFF7C6FF7), strokeWidth: 2.5))
          : _scans.isEmpty
              ? _buildEmptyState()
              : ListView.builder(
                  padding: const EdgeInsets.fromLTRB(16, 12, 16, 24),
                  itemCount: _scans.length,
                  itemBuilder: (context, index) {
                    final scan = _scans[index];
                    return _buildScanCard(scan, index);
                  },
                ),
    );
  }

  Widget _buildEmptyState() {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Container(
            width: 80, height: 80,
            decoration: BoxDecoration(
              color: const Color(0xFF7C6FF7).withOpacity(0.08),
              shape: BoxShape.circle,
            ),
            child: Icon(Icons.insert_chart_outlined_rounded,
                size: 36, color: const Color(0xFF7C6FF7).withOpacity(0.4)),
          ),
          const SizedBox(height: 20),
          const Text(
            "No reports yet",
            style: TextStyle(
              color: Color(0xFF1A2340),
              fontSize: 18,
              fontWeight: FontWeight.w700,
            ),
          ),
          const SizedBox(height: 8),
          const Text(
            "Your AI scan results will show up here\nonce you complete your first analysis.",
            textAlign: TextAlign.center,
            style: TextStyle(
              color: Color(0xFF6B7A99),
              fontSize: 13,
              height: 1.5,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildScanCard(dynamic scan, int index) {
    final date = DateTime.parse(scan['timestamp']);
    final formattedDate = DateFormat('MMM dd, yyyy').format(date);
    final formattedTime = DateFormat('hh:mm a').format(date);
    final confidence = (scan['confidence'] ?? 0.0).toDouble();
    final prediction = scan['prediction'] ?? "Unknown";
    final confColor = _confidenceColor(confidence);
    final confLabel = _confidenceLabel(confidence);

    // Alternate icon colors for visual variety
    final iconColors = [
      const Color(0xFF7C6FF7),
      const Color(0xFF00B894),
      const Color(0xFFFF6FA8),
      const Color(0xFFFFAB2E),
      const Color(0xFFFF6B6B),
    ];
    final cardColor = iconColors[index % iconColors.length];

    return Container(
      margin: const EdgeInsets.only(bottom: 12),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: const Color(0xFFE5EAF4)),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.03),
            blurRadius: 8,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: Padding(
        padding: const EdgeInsets.all(14),
        child: Row(
          children: [
            // Left icon
            Container(
              width: 46,
              height: 46,
              decoration: BoxDecoration(
                color: cardColor.withOpacity(0.10),
                borderRadius: BorderRadius.circular(13),
              ),
              child: Icon(Icons.analytics_rounded, color: cardColor, size: 22),
            ),
            const SizedBox(width: 12),

            // Middle info
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    prediction,
                    style: const TextStyle(
                      color: Color(0xFF1A2340),
                      fontSize: 14,
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                  const SizedBox(height: 4),
                  Row(
                    children: [
                      Icon(Icons.calendar_today_rounded,
                          size: 11, color: const Color(0xFF6B7A99).withOpacity(0.6)),
                      const SizedBox(width: 4),
                      Text(
                        '$formattedDate  ·  $formattedTime',
                        style: TextStyle(
                          color: const Color(0xFF6B7A99).withOpacity(0.8),
                          fontSize: 11,
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 6),
                  // Confidence badge
                  Row(
                    children: [
                      Container(
                        padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                        decoration: BoxDecoration(
                          color: confColor.withOpacity(0.10),
                          borderRadius: BorderRadius.circular(8),
                        ),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            Container(
                              width: 5, height: 5,
                              decoration: BoxDecoration(
                                color: confColor,
                                shape: BoxShape.circle,
                              ),
                            ),
                            const SizedBox(width: 4),
                            Text(
                              '${confidence.toStringAsFixed(1)}%  $confLabel',
                              style: TextStyle(
                                color: confColor,
                                fontSize: 10,
                                fontWeight: FontWeight.w700,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ),

            // PDF button
            GestureDetector(
              onTap: () => _generatePdf(scan),
              child: Container(
                width: 38, height: 38,
                decoration: BoxDecoration(
                  color: const Color(0xFFFF6B6B).withOpacity(0.08),
                  borderRadius: BorderRadius.circular(10),
                ),
                child: const Icon(Icons.picture_as_pdf_rounded,
                    color: Color(0xFFFF6B6B), size: 18),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
