import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../services/api_service.dart';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class ScanHistoryScreen extends StatefulWidget {
  const ScanHistoryScreen({Key? key}) : super(key: key);

  @override
  State<ScanHistoryScreen> createState() => _ScanHistoryScreenState();
}

class _ScanHistoryScreenState extends State<ScanHistoryScreen> {
  bool _isLoading = true;
  List<dynamic> _scans = [];
  String? _userName;

  @override
  void initState() {
    super.initState();
    _fetchHistory();
  }

  Future<void> _fetchHistory() async {
    final SharedPreferences prefs = await SharedPreferences.getInstance();
    final String? token = prefs.getString('userToken');
    _userName = prefs.getString('userName') ?? "Patient";
    
    if (token == null) {
      if (mounted) Navigator.pop(context);
      return;
    }

    final result = await ApiService.getScanHistory(token);
    if (mounted) {
      setState(() {
        if (result['history'] != null) {
          _scans = result['history'];
        }
        _isLoading = false;
      });
    }
  }

  Future<void> _generatePdf(dynamic scan) async {
    final pdf = pw.Document();
    final date = DateTime.parse(scan['timestamp']);
    final formattedDate = DateFormat('MMM dd, yyyy - hh:mm a').format(date);

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(
                level: 0,
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text("DermaAI Analysis Report", style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.teal)),
                    pw.Text("ID: ${scan['id'].toString().substring(0, 8)}"),
                  ],
                ),
              ),
              pw.SizedBox(height: 20),
              pw.Text("Patient Name: $_userName", style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
              pw.Text("Report Date: $formattedDate"),
              pw.Divider(thickness: 1, color: PdfColors.grey300),
              pw.SizedBox(height: 20),
              pw.Text("Analysis Summary", style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 10),
              pw.Container(
                padding: const pw.EdgeInsets.all(16),
                decoration: pw.BoxDecoration(
                  color: PdfColors.teal50,
                  borderRadius: const pw.BorderRadius.all(pw.Radius.circular(10)),
                ),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Row(
                      children: [
                        pw.Text("Detected Condition: ", style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                        pw.Text("${scan['prediction']}"),
                      ],
                    ),
                    pw.SizedBox(height: 8),
                    pw.Row(
                      children: [
                        pw.Text("Confidence Level: ", style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                        pw.Text("${scan['confidence'].toStringAsFixed(2)}%"),
                      ],
                    ),
                  ],
                ),
              ),
              pw.SizedBox(height: 30),
              pw.Text("Medical Note:", style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
              pw.Text(
                "This report is generated by an artificial intelligence model and is intended for informational purposes only. Please consult with a certified dermatologist for clinical diagnosis and treatment planning.",
                style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700),
              ),
              pw.Spacer(),
              pw.Divider(thickness: 0.5),
              pw.Center(child: pw.Text("Generated by DermaAI - Your Personal Skin Assistant", style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey500))),
            ],
          );
        },
      ),
    );

    await Printing.layoutPdf(onLayout: (PdfPageFormat format) async => pdf.save());
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFF0f2027),
      appBar: AppBar(
        title: const Text("Scan History", style: TextStyle(fontWeight: FontWeight.bold, letterSpacing: 1)),
        backgroundColor: Colors.transparent,
        elevation: 0,
        centerTitle: true,
      ),
      body: _isLoading
          ? const Center(child: CircularProgressIndicator(color: Colors.tealAccent))
          : _scans.isEmpty
              ? _buildEmptyState()
              : ListView.builder(
                  padding: const EdgeInsets.all(16),
                  itemCount: _scans.length,
                  itemBuilder: (context, index) {
                    final scan = _scans[index];
                    return _buildScanCard(scan);
                  },
                ),
    );
  }

  Widget _buildEmptyState() {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(Icons.history_rounded, size: 80, color: Colors.white.withOpacity(0.1)),
          const SizedBox(height: 20),
          const Text("No history found", style: TextStyle(color: Colors.white70, fontSize: 18)),
          const SizedBox(height: 10),
          const Text("Your AI analysis results will appear here.", style: TextStyle(color: Colors.white38, fontSize: 14)),
        ],
      ),
    );
  }

  Widget _buildScanCard(dynamic scan) {
    final date = DateTime.parse(scan['timestamp']);
    final formattedDate = DateFormat('MMM dd, yyyy - hh:mm a').format(date);
    final confidence = scan['confidence'] ?? 0.0;
    
    return Container(
      margin: const EdgeInsets.only(bottom: 16),
      decoration: BoxDecoration(
        gradient: LinearGradient(
          colors: [Colors.white.withOpacity(0.05), Colors.white.withOpacity(0.02)],
        ),
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: Colors.white10),
      ),
      child: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Row(
          children: [
            Container(
              width: 60,
              height: 60,
              decoration: BoxDecoration(
                color: Colors.tealAccent.withOpacity(0.1),
                borderRadius: BorderRadius.circular(15),
              ),
              child: const Icon(Icons.analytics_rounded, color: Colors.tealAccent, size: 30),
            ),
            const SizedBox(width: 16),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    scan['prediction'] ?? "Unknown",
                    style: const TextStyle(color: Colors.white, fontSize: 16, fontWeight: FontWeight.bold),
                  ),
                  const SizedBox(height: 4),
                  Text(
                    formattedDate,
                    style: const TextStyle(color: Colors.white38, fontSize: 12),
                  ),
                  const SizedBox(height: 8),
                  Row(
                    children: [
                      Container(
                        padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
                        decoration: BoxDecoration(
                          color: Colors.tealAccent.withOpacity(0.2),
                          borderRadius: BorderRadius.circular(5),
                        ),
                        child: Text(
                          "${confidence.toStringAsFixed(1)}% Confidence",
                          style: const TextStyle(color: Colors.tealAccent, fontSize: 10, fontWeight: FontWeight.bold),
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ),
            IconButton(
              icon: const Icon(Icons.picture_as_pdf, color: Colors.tealAccent),
              onPressed: () => _generatePdf(scan),
            ),
          ],
        ),
      ),
    );
  }
}
